# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://talosiot-will.github.io/repo_template/"

git_url = "https://github.com/talosiot-will/repo_template/tree/master/"

def custom_doc_links(name): return None
